require('iced-coffee-script').register()
_ = require 'taky'

task 'build', 'Build the main JS', ->
  cd __dirname + '/static'
  await exec "iced -cp -I inline main.iced", defer e,out
  _.writes __dirname + '/static/main.js', out.trim()
  log "Finished"
  exit 1

task 'zip', 'Package this site into a .zip file', ->
  cd __dirname
  await exec "zip -r \"#{__dirname + '/../build/php_example_campaign.zip'}\" ./", defer()
  log "Finished"
  exit 1

